#!/usr/bin/env bash
# climcanvas-ports — administration script that combines per-user port
# assignment with the owner-match (nftables) rules, for running ClimCanvas on a
# shared server as "SSH tunnel + per-user process + owner match"
# (see README.en.md in this directory).
#
# A single table, /etc/climcanvas/ports.tsv (user<TAB>port), is the only source
# of truth; every assign regenerates the nftables rules from the whole table
# and applies them.
#
# Usage (as root):
#   climcanvas-ports assign <user> [--port N]  # assign a free port -> append to the table -> apply the rules
#   climcanvas-ports remove <user>             # remove the assignment -> apply the rules
#   climcanvas-ports apply                     # regenerate the nftables rules from the table and apply them
#   climcanvas-ports render                    # print the generated nftables config (without applying it)
#   climcanvas-ports list                      # list the assignments (with UID and listening state)
#
# Environment variables (optional overrides, for tests and custom setups):
#   CLIMCANVAS_PORTS_TABLE  path of the port table  (default /etc/climcanvas/ports.tsv)
#   CLIMCANVAS_NFT_FILE     nft output file         (default /etc/climcanvas/climcanvas.nft)
#   CLIMCANVAS_BASE_PORT    first port to assign    (default 8501)
#   CLIMCANVAS_MAX_PORT     last port to assign     (default 8600)
#   CLIMCANVAS_DRYRUN=1     generate only, do not run nft (no root needed; for checking the output)
set -euo pipefail

TABLE="${CLIMCANVAS_PORTS_TABLE:-/etc/climcanvas/ports.tsv}"
NFT_FILE="${CLIMCANVAS_NFT_FILE:-/etc/climcanvas/climcanvas.nft}"
BASE_PORT="${CLIMCANVAS_BASE_PORT:-8501}"
MAX_PORT="${CLIMCANVAS_MAX_PORT:-8600}"
DRYRUN="${CLIMCANVAS_DRYRUN:-0}"

die() { echo "error: $*" >&2; exit 1; }

# Print the effective rows of the table (comments and blank lines removed) as "user port".
# awk alone does the job (grep exits 1 on no match, which would trip pipefail + set -e).
read_entries() {
    [ -f "$TABLE" ] || return 0
    awk 'NF && $1 !~ /^#/ {print $1, $2}' "$TABLE"
}

lookup_port() {  # user -> port (empty if none)
    read_entries | awk -v u="$1" '$1==u {print $2; exit}'
}

port_taken() {   # true if the port is in the table
    read_entries | awk -v p="$1" '$2==p {found=1} END{exit found?0:1}'
}

next_free_port() {
    local p
    for ((p=BASE_PORT; p<=MAX_PORT; p++)); do
        if ! port_taken "$p"; then echo "$p"; return 0; fi
    done
    die "no free port in the range $BASE_PORT-$MAX_PORT"
}

resolve_uid() {  # user -> uid (error if the user does not exist)
    id -u "$1" 2>/dev/null || die "user '$1' does not exist"
}

need_root() {
    [ "$DRYRUN" = 1 ] && return 0
    [ "$(id -u)" = 0 ] || die "this operation needs root (or CLIMCANVAS_DRYRUN=1)"
}

ensure_table_dir() {
    local d; d="$(dirname "$TABLE")"
    [ -d "$d" ] || mkdir -p "$d"
    [ -f "$TABLE" ] || {
        printf '# ClimCanvas port assignment table  user<TAB>port\n' > "$TABLE"
    }
}

# Generate the nftables config from the whole table and print it to stdout.
render() {
    cat <<'EOF'
#!/usr/sbin/nft -f
# Generated by climcanvas-ports. Do not edit by hand; update it with climcanvas-ports.
# The dedicated table is flushed and rebuilt, so other firewall settings are left untouched.
add table inet climcanvas
flush table inet climcanvas
table inet climcanvas {
    chain output {
        type filter hook output priority 0; policy accept;
EOF
    local user port uid
    while read -r user port; do
        [ -n "$user" ] || continue
        uid="$(resolve_uid "$user")"
        printf '        # %s (uid %s) -> loopback:%s: only the owner and root\n' "$user" "$uid" "$port"
        printf '        oif "lo" tcp dport %s meta skuid %s accept\n' "$port" "$uid"
        [ "$uid" = 0 ] || printf '        oif "lo" tcp dport %s meta skuid 0 accept\n' "$port"
        printf '        oif "lo" tcp dport %s reject with tcp reset\n' "$port"
    done < <(read_entries)
    cat <<'EOF'
    }
}
EOF
}

apply() {
    need_root
    ensure_table_dir
    local tmp; tmp="$(mktemp)"
    render > "$tmp"
    mkdir -p "$(dirname "$NFT_FILE")"
    mv "$tmp" "$NFT_FILE"
    if [ "$DRYRUN" = 1 ] || ! command -v nft >/dev/null 2>&1; then
        echo "[dry-run] generated $NFT_FILE (nft not run: DRYRUN is set or nft is not installed)"
        return 0
    fi
    nft -f "$NFT_FILE"
    echo "applied the owner-match rules from $TABLE ($NFT_FILE)"
}

hint() {  # print how the user connects
    local user="$1" port; port="$(lookup_port "$user")"
    cat <<EOF

--- How $user runs ClimCanvas ---------------------------------------
On the server (as $user):
  climcanvas-ports is done; start ClimCanvas under your own account:
  streamlit run app.py --server.headless=true --server.address=127.0.0.1 --server.port=$port
  (scripts/server/start-climcanvas.sh fills in the port automatically)

From your machine:
  ssh -L $port:localhost:$port $user@<server>
  then open http://localhost:$port in a browser
--------------------------------------------------------------------
EOF
}

cmd_assign() {
    local user="${1:-}" want=""
    [ -n "$user" ] || die "usage: climcanvas-ports assign <user> [--port N]"
    shift || true
    while [ $# -gt 0 ]; do
        case "$1" in
            --port) want="${2:-}"; shift 2 ;;
            *) die "unknown option: $1" ;;
        esac
    done
    resolve_uid "$user" >/dev/null   # make sure the user exists
    ensure_table_dir
    local existing; existing="$(lookup_port "$user")"
    if [ -n "$existing" ]; then
        echo "$user already has port $existing"
    else
        local port
        if [ -n "$want" ]; then
            [[ "$want" =~ ^[0-9]+$ ]] || die "--port must be a number"
            { [ "$want" -ge "$BASE_PORT" ] && [ "$want" -le "$MAX_PORT" ]; } \
                || die "--port must be within $BASE_PORT-$MAX_PORT"
            ! port_taken "$want" || die "port $want is already assigned"
            port="$want"
        else
            port="$(next_free_port)"
        fi
        printf '%s\t%s\n' "$user" "$port" >> "$TABLE"
        echo "assigned port $port to $user"
    fi
    apply
    hint "$user"
}

cmd_remove() {
    local user="${1:-}"
    [ -n "$user" ] || die "usage: climcanvas-ports remove <user>"
    [ -f "$TABLE" ] || die "port table not found: $TABLE"
    local tmp; tmp="$(mktemp)"
    awk -v u="$user" '($0 ~ /^[[:space:]]*(#|$)/) || $1!=u' "$TABLE" > "$tmp"
    mv "$tmp" "$TABLE"
    echo "removed the assignment of $user"
    apply
}

cmd_list() {
    printf '%-16s %-6s %-8s %s\n' USER PORT UID LISTENING
    local user port uid st
    while read -r user port; do
        uid="$(id -u "$user" 2>/dev/null || echo '?')"
        if command -v ss >/dev/null 2>&1 \
           && ss -tlnH "sport = :$port" 2>/dev/null | grep -q .; then
            st=yes
        elif command -v ss >/dev/null 2>&1; then
            st=no
        else
            st='?'
        fi
        printf '%-16s %-6s %-8s %s\n' "$user" "$port" "$uid" "$st"
    done < <(read_entries)
}

main() {
    local sub="${1:-}"; shift || true
    case "$sub" in
        assign) cmd_assign "$@" ;;
        remove) cmd_remove "$@" ;;
        apply)  apply ;;
        render) render ;;
        list)   cmd_list ;;
        ""|-h|--help)
            grep -E '^#( |$)' "$0" | sed -E 's/^# ?//' ;;
        *) die "unknown command: $sub (see --help)" ;;
    esac
}

main "$@"
